### ISSUE TITLE
The example/extension does not work

### ISSUE THREAD

**Issue by Arrowana** [wallet-standard/wallet-standard#65]
https://github.com/wallet-standard/wallet-standard/tree/master/packages/example/extension

After building (pnpm build) and adding the extension to chrome, the console shows an error
```
Uncaught Error: Cannot find module 'ixBAX'
    at o (content.3e113068.js:1:452)
    at runtime-9f27d6504f69d7a6.js:1:58
    at index.ts:12:6
```
![Screenshot from 2022-10-20 10-43-19](https://user-images.githubusercontent.com/8245419/196824794-c6bf4e3a-72f4-469e-9143-2ef470b159f9.png)

In addition the field `window.wallets` in undefined

**Comment by jordansexton** [comment]
@olistic any idea what's happening here?

**Comment by jordansexton** [comment]
Leaving this for @olistic to pick up since he's the author of the extension and is more familiar with the architecture than me.

<img width="352" alt="Screen Shot 2022-10-19 at 7 14 50 PM" src="https://user-images.githubusercontent.com/1173161/196834316-9d03b272-1ff8-4370-8956-c5549509179f.png">
Extension popup seems to work.

But I get the same error as OP from the contentScript. Using `parcel build --no-optimize` to eliminate minification, I get this:
<img width="357" alt="Screen Shot 2022-10-19 at 7 43 14 PM" src="https://user-images.githubusercontent.com/1173161/196834473-b418b2ca-7c1c-4e9d-bfd7-10a0bc00f6b9.png">

Indicating an error with dependency resolution on line 1 of this:
<img width="425" alt="Screen Shot 2022-10-19 at 7 43 31 PM" src="https://user-images.githubusercontent.com/1173161/196834483-3e699c5f-a9e3-42a3-9940-0fe967565e97.png">

I also see duplicate builds with content hashes in the `dist` dir:
<img width="249" alt="Screen Shot 2022-10-19 at 8 20 55 PM" src="https://user-images.githubusercontent.com/1173161/196834530-6a7a5ce5-0f42-4268-86a5-7d6c60b9e47a.png">

This persists even with `parcel build --no-optimize --no-content-hash --no-cache`
